citizenship_lists:
  - Albanian
  - Algerian
  - American
  - Andorran
  - Angolan
  - Antiguans
  - Argentinean
  - Armenian
  - Australian
  - Austrian
  - Azerbaijani
  - Bahamian
  - Bahraini
  - Russian
  - Belizean
  - Beninese
  - Bhutanese
  - Bolivian
  - Bosnian
  - Brazilian
  - British
  - Bruneian
  - Bulgarian
  - Burkinabe
  - Burmese
  - Burundian
  - Cambodian
  - Cameroonian
  - Canadian
  - CapeVerdean
  - CentralAfrican
  - Chadian
  - Chilean
  - Chinese
  - Colombian
  - Comoran
  - Congolese
  - CostaRican
  - Croatian
  - Cuban
  - Cypriot
  - Czech
  - Danish
  - Djibouti
  - Dominican
  - Dutch
  - EastTimorese
  - Ecuadorean
  - Egyptian
  - Emirian
  - EquatorialGuinean
  - Eritrean
  - Estonian
  - Ethiopian
  - Fijian
  - Filipino
  - Finnish
  - French
  - Gabonese
  - Gambian
  - Georgian
  - German
  - Ghanaian
  - Greek
  - Grenadian
  - Guatemalan
  - Guinea-Bissauan
  - Guinean
  - Guyanese
  - Herzegovinian
  - Honduran
  - Hungarian
  - Icelander
  - Indonesian
  - Iranian
  - Iraqi
  - Irish
  - Israeli
  - Italian
  - Ivorian
  - Jamaican
  - Japanese
  - Jordanian
  - Kazakhstani
  - Kenyan
  - KittianandNevisian
  - Kuwaiti
  - Kyrgyz
  - Laotian
  - Latvian
  - Lebanese
  - Liberian
  - Libyan
  - Luxembourger
  - Macedonian
  - Malagasy
  - Malawian
  - Malaysian
  - Maldivan
  - Malian
  - Maltese
  - Mauritanian
  - Mauritian
  - Mexican
  - Micronesian
  - Moldovan
  - Monacan
  - Mongolian
  - Moroccan
  - Mosotho
  - Motswana
  - Mozambican
  - Namibian
  - Nauruan
  - Nepalese
  - NewZealander
  - Nicaraguan
  - Nigerian
  - Nigerien
  - NorthKorean
  - NorthernIrish
  - Norwegian
  - Omani
  - Palauan
  - Panamanian
  - PapuaNewGuinean
  - Paraguayan
  - Peruvian
  - Polish
  - Portuguese
  - Qatari
  - Romanian
  - Russian
  - Rwandan
  - SaintLucian
  - Salvadoran
  - Samoan
  - SanMarinese
  - SaoTomean
  - Saudi
  - Scottish
  - Senegalese
  - Serbian
  - Seychellois
  - SierraLeonean
  - Singaporean
  - Slovakian
  - Slovenian
  - SolomonIslander
  - Somali
  - SouthAfrican
  - SouthKorean
  - Spanish
  - SriLankan
  - Sudanese
  - Surinamer
  - Swazi
  - Swedish
  - Swiss
  - Syrian
  - Taiwanese
  - Tajik
  - Tanzanian
  - Thai
  - Togolese
  - Tongan
  - Trinidadianor
  - Tobagonian
  - Tunisian
  - Turkish
  - Tuvaluan
  - Ugandan
  - Ukrainian
  - Uruguayan
  - Uzbekistani
  - Vietnamese
  - Welsh
  - Yemenite
  - Zambian
  - Zimbabwean

country_lists:
  - Afghanistan
  - Albania
  - Algeria
  - AmericanSamoa
  - Andorra
  - Angola
  - Anguilla
  - AntiguaandBarbuda
  - Argentina
  - Armenia
  - Aruba
  - Australia
  - Austria
  - Azerbaijan
  - Bahamas
  - Bahrain
  - Bangladesh
  - Barbados
  - Belarus
  - Belgium
  - Belize
  - Benin
  - Bermuda
  - Bhutan
  - Bolivia
  - Botswana
  - BouvetIsland
  - Brazil
  - Brunei
  - Bulgaria
  - BurkinaFaso
  - Burundi
  - Cambodia
  - Cameroon
  - Canada
  - CapeVerde
  - CaymanIslands
  - Chad
  - Chile
  - China
  - ChristmasIsland
  - CocosIslands
  - Colombia
  - Comoros
  - Congo 
  - CookIslands
  - CostaRica
  - Croatia
  - Cuba
  - Cyprus
  - CzechRepublic
  - Denmark
  - Djibouti
  - Dominica
  - DominicanRepublic
  - Ecuador
  - Egypt
  - ElSalvador
  - EquatorialGuinea
  - Eritrea
  - Estonia
  - Ethiopia
  - FalklandIslands
  - FaroeIslands
  - Fiji
  - Finland
  - France
  - FrenchGuiana
  - Gabon
  - Gambia
  - Georgia
  - Germany
  - Ghana
  - Greece
  - Greenland
  - Grenada
  - Guam(USA)
  - Guatemala
  - Guinea
  - GuineaBissau
  - Guyana
  - Haiti
  - HolySee
  - Honduras
  - HongKong
  - Hungary
  - Iceland
  - India
  - Indonesia
  - Iran
  - Iraq
  - Ireland
  - Israel
  - Ita
  - Jamaica
  - Japan
  - Jordan
  - Kazakhstan
  - Kenya
  - Kiribati
  - Kuwait
  - Kyrgyzstan
  - Laos
  - Latvia
  - Lebanon
  - Lesotho
  - Liberia
  - Libya
  - Liechtenstein
  - Lithuania
  - Luxembourg
  - Macau
  - Macedonia
  - Madagascar
  - Malawi
  - Malaysia
  - Maldives
  - Mali
  - Malta
  - Mauritania
  - Mauritius
  - Mayotte
  - Mexico
  - Micronesia
  - Moldova
  - Monaco
  - Mongolia
  - Montenegro
  - Montserrat
  - Morocco
  - Mozambique
  - Myanmar
  - Namibia
  - Nauru
  - Nepal
  - Netherlands
  - NewZealand
  - Niger
  - Nigeria
  - Niue
  - NorfolkIsland
  - NorthKorea
  - Norway
  - Oman
  - Pakistan
  - Palau
  - Panama
  - PapuaNewGuinea
  - Paraguay
  - Peru
  - Philippines
  - PitcairnIsland
  - Poland
  - Polynesia(French)
  - Portugal
  - PuertoRico
  - Qatar
  - Reunion
  - Romania
  - Russia
  - Rwanda
  - SaintHelena
  - SaintLucia
  - Samoa
  - SanMarino
  - SaoTomeandPrincipe
  - SaudiArabia
  - Senegal
  - Serbia
  - Seychelles
  - SierraLeone
  - Singapore
  - Slovakia
  - Slovenia
  - SolomonIslands
  - Somalia
  - SouthAfrica
  - SouthKorea
  - SouthSudan
  - Spain
  - SriLanka
  - Sudan
  - Suriname
  - Swaziland
  - Sweden
  - Switzerland
  - Syria
  - Taiwan
  - Tajikistan
  - Tanzania
  - Thailand
  - Togo
  - Tokelau
  - Tonga
  - Turkey
  - Turkmenistan
  - Tuvalu
  - Uganda
  - Ukraine
  - UnitedKingdom
  - UnitedStates
  - Uruguay
  - Uzbekistan
  - Vanuatu
  - Venezuela
  - Vietnam
  - VirginIslands
  - Yemen
  - Zambia
  - Zimbabwe
